language: node_js
node_js:
- '6'
notifications:
  slack:
    secure: XJ69aD1qJ7r5LLltB8IdqWcvROqHkB46wYPhvphgbc2yXPTBnXar8C70BQHzkj042/6LjuN4ETbYvctLOhN0a7742FrsZePfvKz1CUTNBFJOozQdZR4CZBBFT3qpvYyIVwv0hnW53HWrew7DHsmrvXkK58wkeoZr1S/12jy8ZPA2/K0Ox4J6b0dJYUErAShamghfquHHn7EnCZNFX62wUBEMorwKZ/PdWJcFJ3fi654UuehchG05k30S0QQi6YasEp3QraCcw2oFsmmxb/viGe6N93Hlub2k63scFQMc34GRUiw3VxjYS3yJuLm0NGuYDOHao4MQBCulOomABwmdjewHzIU4TMaUulthQq0+cD8ZgH66oWnYbHM67pNCKBqV1ifwf+VgcPb2xizieM3F+GAVTpzX/5r8n8383O9HDBhEAG1UcYlnrIPisWVFA6XTJgtbGXEoNw+5jhX0CIFuhx6hcWEEZifOYxQZYjJ+Rd/+ZK5tpuUxPtjZ7SDg0CwH8cOTI/Kp3yXxhEmxfd85qB9edSnfkRE5zZmdbAIfWpFlKTuXRLDVGjgTnSzWU7Q2fQiQcfGjy41v69a8Jy78EOQKWixqgZsKb6eMpR+2o5+G7foTi/Nsp5RvfIPz7VK+se31xjk+Dpmhf5I5kRrcghdoBz4N8bSDlP88n0dZKIc=
